### ISSUE TITLE
Switch to Harmony for detouring

### ISSUE THREAD

**Issue by DaEgi01** [ST-Apps/CS-ParallelRoadTool#24]
https://github.com/pardeike/Harmony

Imo harmony is superior to the current solution, since it allows multiple detourings to work together without conflicts and determine the order in which they are executed.
Check it out.

**Comment by ST-Apps** [comment]
> it allows multiple detourings to work together without conflicts and determine the order in which they are executed.

Does it work also with other mods that are not using Harmony?
For example, let's say that a certain mod enables a detour on a method without using Harmony.
If I switch to Harmony, will I be able to say that my detour should be executed before or after the one's from the other mod?

I tried Harmony in the very first PoC that I did for this mod, but I ended up with the current solution because it was easier.

**Comment by DaEgi01** [comment]
> Does it work also with other mods that are not using Harmony?

No it only works if all detours are done with harmony, which is why it's so important IMO that every mod that does detouring switches to that lib.
