### ISSUE TITLE
Find a better name

### ISSUE THREAD

**Issue by ST-Apps** [ST-Apps/CS-ParallelRoadTool#6]
Now that vertical stacking is supported, _ParallelRoadTool_ is not the best name out there.

**Comment by torchatlas** [comment]
Viciniroad

**Comment by severeguest** [comment]
Better Road Placement

**Comment by mfkolb** [comment]
Pararoad!

**Comment by BadiBasso** [comment]
Multi Road Tool.
Similar to Fine Road Tool which is not restricted to roads only.

**Comment by MiracleBlue** [comment]
Parallel road tool is a fine name, unless you wanted to call it something mythic like Valkyrie or Valhalla or some badass name like that.

**Comment by pkej** [comment]
I think PRT is good, but since it works on all networks, perhaps something which reflects that as well? I don't know what is best from a "marketing point" in the Steam-shop, I guess most people would like it for transport networks, as for example water and power lines give strange results both as a part of a setup, or when used and the PLT is on.
