### ISSUE TITLE
Broken button

### ISSUE THREAD

**Issue by Mazeballz** [ST-Apps/CS-ParallelRoadTool#63]
Button quits working rendering menu stuck open/closed. Button is also in the incorrect location? Due to the nature of this issue, I've made a video rather than taking screenshots. Follow the youtube address for that. Also, the output log was generated at the time of the video. This issue occurs with both 1.2 and 1.2.1-Dev

https://www.youtube.com/watch?v=YM0tHrtuldw
[output_log.txt](https://github.com/ST-Apps/CS-ParallelRoadTool/files/2288369/output_log.txt)

**Comment by ST-Apps** [comment]
Thanks for the report.

- Button's position is correct, I moved it a few versions ago because it was overlapping another mod's button. You can still move it as you wish, just right click and drag.

- I can't reproduce your issue, but judging from your log I may have released a wrong version so I'm updating it now. What happens if you go back to roads instead of water? Does the button start working again?

**Comment by Mazeballz** [comment]
Oh cool.  No it doesn't work after switching back to roads. Technically
speaking I can break it workout switching off roads simply by clicking the
other road tools and tutorial button while I click it off and on.

I seen at least one other guy mention something similar.

I used to mod for Oblivion and this reminds me of an issue i ran into those
many moons ago.

This involves a script right? Mind copying and pasting the script/section
that deals with the button activating the tool menu? I'd like to see it as
I think I may have a few lines to suggest that may fix the issue for us
unlucky few.

**Comment by ST-Apps** [comment]
Just got back from holidays, I'll need a few days to get back on track but I'll try to reproduce the issue asap.
